### ISSUE TITLE
Unknown type "Button" Build Error when trying to use XCC

### ISSUE THREAD

**Issue by MarkDHarris** [firstfloorsoftware/xcc#1]
I am using Microsoft P&P Prism in a universal store/phone app, working in a VisualStateAwarePage and trying to use xcc.  I think I have followed the sample correctly but xcc does not work as easily as the docs suggest and I am left with a strange build error.

After following the sample, I have a page like this:

<prism:VisualStateAwarePage
    x:Class="Project1.Views.Page1"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:interactivity="using:Microsoft.Xaml.Interactivity"
    xmlns:core="using:Microsoft.Xaml.Interactions.Core"
    xmlns:converters="using:Project1.Converters"
    xmlns:prism="using:Microsoft.Practices.Prism.StoreApps" 
    xmlns:prismMvvm="using:Microsoft.Practices.Prism.Mvvm"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:win81="condition:WINDOWS_APP"
    xmlns:wp81="condition:WINDOWS_PHONE_APP"
    xmlns:debug="condition:DEBUG"
    xmlns:release="condition:!DEBUG"
    mc:Ignorable="d win81 wp81 debug release"
    mc:ProcessContent="d win81:* wp81:* debug:* release:*"
    prismMvvm:ViewModelLocator.AutoWireViewModel="true" >

Then on the page,  have a button that I only want to show in DEBUG mode.
   <debug:Button ... stuff ...  />

And I get this build error:

Error   4   Unknown type 'Button' in XML namespace 'using:Microsoft.Practices.Prism.StoreApps'  C:\PROJECTS\Project1.WindowsPhone\obj\x86\Debug\preprocessedxaml\Views\Page1.xaml   60  14  Project1.WindowsPhone

Has anyone seen this or have any insight about what is wrong?

Thanks

**Comment by kozw** [comment]
Your XAML looks fine. Can you share how the Button is defined in XAML?

**Comment by MarkDHarris** [comment]
I defined a button like this: 
           <debug:Button Grid.Row="1" 
                    Content="Test Button" 
                    Command="{Binding TestCommand}" />

Which immediately leads to this error:
     XamlCompiler error WMC0001: Unknown type 'Button' in XML 
       namespace 'using:Microsoft.Practices.Prism.StoreApps'

I have tracked down the problem to the fact that my pages are inheriting not from Windows.UI.Xaml.Controls.Page but from Microsoft.Practices.Prism.StoreApps.VisualStateAwarePage. I do that because I am using Microsoft's Patterns and Practices Prism library and following the MVVM pattern.

To eliminate complexity, I created a second, simple test project and found it to work exactly as it should. I then proceeded to modify the out of the box universal project from the code behind pattern to the use of Prism and at the moment I changed the page to inherit from the VisualStateAwarePage I got this error again.  

So, I think the problem is that the XCC compiler assumes that the button is defined in the same namespace as where the page that the button is sitting on is defined. In my case, Microsoft.Practices.Prism.StoreApps.VisualStateAwarePage does inherit from Page but it is much farther down in the hierarchy than normal.  

Is there an order of precedence or alternative way to help the XCC complier find where the button is defined if I'm not using the expected Page class?

**Comment by kozw** [comment]
Got it, XCC translates conditional elements to the namespace of the root element. Since your page root element is defined in the `using:Microsoft.Practices.Prism.StoreApps` namespace, the conditional Button is rewritten to that namespace. Exactly what the error message is describing.

Interesting bug, which requires some thinking.

Thanks for reporting
