### ISSUE TITLE
Problem with SHA512 key of NuGet package

### ISSUE THREAD

**Issue by WilfriedRicken** [firstfloorsoftware/xcc#15]
Hi,

when including xcc via project.json approach into projects, we have problems with the SHA512 key of the package. It switches randomly between the following two values:

QyHC1jD1G7kThM+GrabUM1T7jREwsCVrx3odrjjbQAI0+w1+/zdFap3Isz/rT+wOJB3Uirrc/13d4ly8GcJr4Q==

3TeYAfw7/4x2zoiNtKnQQmxgDN3fXL9/w3Z087xwvQ0mWwEd/D8c16wIG4CbdcPThc7xMOQOvgKr3qLrOWePDA==

This doesn't happen to any other NuGet package in our projects, so there must be something weird in the xcc package.

A sample project.json file looks like this:

{
  "dependencies": {
    "log4net": "2.0.5",
    "xcc": "1.0.8"
  },
  "frameworks": {
    "net461": {}
  },
  "runtimes": {
    "win": {}
  }
}

Thanks,
Wilfried

**Comment by kozw** [comment]
Interesting. Are you saying the xcc.1.0.8.nupkg.sha512 file on disk has different values? As far as I can tell, it should be `QyHC1jD1G7kThM+GrabUM1T7jREwsCVrx3odrjjbQAI0+w1+/zdFap3Isz/rT+wOJB3Uirrc/13d4ly8GcJr4Q==`

I'm not sure this has anything todo with xcc itself

**Comment by WilfriedRicken** [comment]
Yes. I included the file for your reference. The interesting part is that this only happens for xcc, no other nuget package hast hat behavior. Andy yes, sometimes it contains the value Q…

**Comment by WilfriedRicken** [comment]
Another interesting aspect: Calculating the SHA512 key for the nupkg file results in 3TeYAfw7/4x2zoiNtKnQQmxgDN3fXL9/w3Z087xwvQ0mWwEd/D8c16wIG4CbdcPThc7xMOQOvgKr3qLrOWePDA==, not in QyHC1jD1G7kThM+GrabUM1T7jREwsCVrx3odrjjbQAI0+w1+/zdFap3Isz/rT+wOJB3Uirrc/13d4ly8GcJr4Q==

**Comment by WilfriedRicken** [comment]
So I suppose the following is true: The correct SHA512 key should be 3..., but on NuGet you supply a file with Q...

**Comment by kozw** [comment]
I just released v1.0.9 of xcc which is just a complete rebuild of the package. Something might have gone wrong with the previous version. Please try and see whether the erratic behavior still appears.

**Comment by WilfriedRicken** [comment]
Downloaded the new version, and actually it looks good. The new SHA512 key is now O7xi8u3sJQEZmNcgcUEiC3F7BU36Eo/NvKCLjBIU17vlkAavyBwlRKACDjPy7JBkQe+MuLrXALGgclnASzCTwA== in all cases.

**Comment by kozw** [comment]
Good, I'm closing the issue.

**Comment by WilfriedRicken** [comment]
Yes. I included the file for your reference. The interesting part is that this only happens for xcc, no other nuget package hast hat behavior. Andy es, sometimes it contains the value Q…

Best regards,
Wilfried

Von: Koen Zwikstra [mailto:notifications@github.com]
Gesendet: Donnerstag, 20. Oktober 2016 17:45
An: firstfloorsoftware/xcc xcc@noreply.github.com
Cc: Wilfried Ricken Wilfried.Ricken@maximago.de; Author author@noreply.github.com
Betreff: Re: [firstfloorsoftware/xcc] Problem with SHA512 key of NuGet package (#15)

Interesting. Are you saying the xcc.1.0.8.nupkg.sha512 file on disk has different values? As far as I can tell, it should be QyHC1jD1G7kThM+GrabUM1T7jREwsCVrx3odrjjbQAI0+w1+/zdFap3Isz/rT+wOJB3Uirrc/13d4ly8GcJr4Q==

I'm not sure this has anything todo with xcc itself

**Comment by WilfriedRicken** [comment]
Another interesting aspect: Calculating the SHA512 key for the nupkg file results in 3TeYAfw7/4x2zoiNtKnQQmxgDN3fXL9/w3Z087xwvQ0mWwEd/D8c16wIG4CbdcPThc7xMOQOvgKr3qLrOWePDA==, not in QyHC1jD1G7kThM+GrabUM1T7jREwsCVrx3odrjjbQAI0+w1+/zdFap3Isz/rT+wOJB3Uirrc/13d4ly8GcJr4Q==.

Best regards,
Wilfried

Von: Koen Zwikstra [mailto:notifications@github.com]
Gesendet: Donnerstag, 20. Oktober 2016 17:45
An: firstfloorsoftware/xcc xcc@noreply.github.com
Cc: Wilfried Ricken Wilfried.Ricken@maximago.de; Author author@noreply.github.com
Betreff: Re: [firstfloorsoftware/xcc] Problem with SHA512 key of NuGet package (#15)

Interesting. Are you saying the xcc.1.0.8.nupkg.sha512 file on disk has different values? As far as I can tell, it should be QyHC1jD1G7kThM+GrabUM1T7jREwsCVrx3odrjjbQAI0+w1+/zdFap3Isz/rT+wOJB3Uirrc/13d4ly8GcJr4Q==

I'm not sure this has anything todo with xcc itself
