### ISSUE TITLE
The property ProcessContent was not found in type UserControl

### ISSUE THREAD

**Issue by igorkulman** [firstfloorsoftware/xcc#2]
I integrated XCC to my project according to the manual and the designer stopped working, showing "The property ProcessContent was not found in type UserControl" in all the DataTemplates and UserControls that use XCC. Everything works fine at runtime.

**Comment by kozw** [comment]
In what type of project is this happening?

**Comment by igorkulman** [comment]
Universal app, in both win81 and wp81

**Comment by kozw** [comment]
I've tried to reproduce this in VS2013 on a UserControl in a universal project, but it seems to work fine. Are you sure you have defined both mc:Ignorable and mc:ProcessContent? This is what my UserControl xaml looks like:

``` xml
<UserControl
    x:Class="App2.MyUserControl"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:local="using:App2"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:win81="condition:WINDOWS_APP"
    xmlns:wp81="condition:WINDOWS_PHONE_APP"
    mc:Ignorable="d win81 wp81"
    mc:ProcessContent="win81:* wp81:*"
    d:DesignHeight="300"
    d:DesignWidth="400">
</UserControl>
```

**Comment by igorkulman** [comment]
I have two UserControl using XCC, EbookListingItem and EbookDownloadButton. When I open EbookDownloadButton in the designer, no error is shown. But when I open EbookListingItem  which include EbookDownloadButton, I get this:

![error](https://cloud.githubusercontent.com/assets/4746070/6655979/cfec9558-cb17-11e4-9dd3-c20e3366e03a.png)

The EbookDownloadButton by itself looks good, no error, the XAML is as it should:

``` xml
<UserControl
    x:Class="AlzaMedia.Controls.Buttons.EbookDownloadButton"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:micro="using:Caliburn.Micro"
    xmlns:win81="condition:WINDOWS_APP"
    xmlns:wp81="condition:WINDOWS_PHONE_APP"
    mc:Ignorable="d win81 wp81"
    mc:ProcessContent="win81:* wp81:*"
    d:DesignHeight="300"
    d:DesignWidth="400">
```

**Comment by kozw** [comment]
The designer might complain, but the resulting XAML works and compiles fine.
