### ISSUE TITLE
Xamarin.Forms 1.3.5?

### ISSUE THREAD

**Issue by Mike-E-angelo** [firstfloorsoftware/xcc#3]
Hello,

I am curious if XCC is supposed to work with the latest Xamarin.Forms (as of today 1.3.5).  I just tried it in a project, and I am getting the following exception when I load a xaml file with its attributes defined:

---

A first chance exception of type 'Xamarin.Forms.Xaml.XamlParseException' occurred in Xamarin.Forms.Xaml.DLL

Additional information: Position 2:391. No Property of name Ignorable found

---

Any guidance/insight would be greatly appreciated.  It turns out that XF does not support Ignorable out of the box, so we're missing out on DesignInstanceExtention at the moment.  Looking for viable work-arounds. :)

Here's the link for more info, if interested: https://bugzilla.xamarin.com/show_bug.cgi?id=27295

**Comment by kozw** [comment]
Not sure, I'll need to check that. The behavior of XCC is such that it should remove the mc:Ignorable attribute from the XAML.

**Comment by Mike-E-angelo** [comment]
Hm... something is wrong, then.  The xcc .targets file was listed below the Xamarin.Forms.targets, but moving it before doesn't do anything (not that I think it matters).  I do see a preprocessedxaml folder, but the xaml that is found in there does indeed have the Ignorable tag.

Cool to see that you do remove it, though. :)  If we can figure out the problem here I can update the issue on Xamarin's forums to point to this project as the fix until the XF team can look into it.

Do you know if your Task would also remove uses of the DesignInstanceExtension as well?

**Comment by kozw** [comment]
XCC removes mc:ProcessContent and all custom condition namespaces. For mc:Ignorable, I was speaking too soon, it only removes this attribute when its value is empty after removing the condition namespace prefixes. What does your Ignorable attribute look like in the preprocessedxaml folder?

DesignInstanceExtension is untouched.

**Comment by Mike-E-angelo** [comment]
OK that makes sense, then.  Here is a sample before:

```
<Application xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:win81="condition:WINDOWS_APP"
  xmlns:wp81="condition:WINDOWS_PHONE_APP"
  mc:Ignorable="d win81 wp81"
  mc:ProcessContent="win81:* wp81:*"
    xmlns:formsGallery="clr-namespace:FormsGallery;assembly=FormsGallery"
    xmlns:support="clr-namespace:FormsGallery.Support;assembly=FormsGallery"
    x:Class="FormsGallery.App">
```

And after:

```
<Application xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:d="http://schemas.microsoft.com/expression/blend/2008" mc:Ignorable="d" xmlns:formsGallery="clr-namespace:FormsGallery;assembly=FormsGallery" xmlns:support="clr-namespace:FormsGallery.Support;assembly=FormsGallery" x:Class="FormsGallery.App">
```

So it is doing exactly what it "should" be.  However, if you could find someway of making it strip out _all_ "Ignorables" it would be greatly appreciated. :)  Again, _any_ Ignorables that remain are actually an exception state in Xamarin.Forms currently.  So if it's possible to strip them out relatively easily during your process, then that would be awesome!  Otherwise, no worries.

**Comment by kozw** [comment]
XCC is surely capable of removing the Ignorable attribute. And I'm trying to think of a more generic solution, where you could specify that an entire xmlns should be removed from the XAML. In your case you should be able to specified that all references to  `http://schemas.microsoft.com/expression/blend/2008` should be removed. 

Not sure yet how this could be configured. Any thoughts?

**Comment by Mike-E-angelo** [comment]
Well that's just it, right?  If you add XCC to your project, it functions exactly like it does now, but removes all the ignorables during its preprocessing task.

Ignorables are meant to be ignored during runtime.  So they should be stripped out anyways by default.  If you want to maintain them (that is, to NOT have Xcc strip out content defined in mc:Ignorable), then I would do something like:

```
<Application xmlns="http://xamarin.com/schemas/2014/forms"
    xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:xcc="https://github.com/firstfloorsoftware/xcc"
  mc:Ignorable="d win81 wp81 xcc"
  mc:ProcessContent="win81:* wp81:*"
xcc:RemoveIgnorableContent="false"
...>
```

You could also make it a configurable project-wide setting in MSBuild:

```
<XccRemoveIgnorableContent>True</XccRemoveIgnorableContent>
```

Those are my thoughts, at least. :)

**Comment by kozw** [comment]
I really like that xcc:RemoveIgnorableContent approach. I'll see if there's any cons here, and otherwise continue to implement it

**Comment by Mike-E-angelo** [comment]
Awesome!  Let me know if I can assist in any further way. :+1:

**Comment by Mike-E-angelo** [comment]
Wow!  That was quick. :)  I am looking through the code and I don't see any tests specifically around markup extensions... I might have missed it though... will this remove the DesignInstanceExtension?

**Comment by kozw** [comment]
Implemented the global project option. See also https://github.com/firstfloorsoftware/xcc/wiki/Remove-ignorable-content

**Comment by kozw** [comment]
As long as DesignInstanceExtension is defined in a namespace referenced in mc:Ignorable, it will be removed from the output. You should be good when having attribute `d:DesignInstance` and `mc:Ignorable="d"`.

**Comment by Mike-E-angelo** [comment]
DUDE!  Works like a champ!  Much respect and appreciation to you, good sir.  That is really quite impressive!  I don't think I've seen such a told turnaround on a feature like that before.  VERY much appreciated!  I will update Xamarin.Forms forums accordingly. :)  Thanks again!

**Comment by Mike-E-angelo** [comment]
My only suggestion is that XccRemoveIgnorableContent should be True by default... That way we can just add Xcc to our projects and be done with it.  Currently we have to add it and then update the csproj (kind of a hassle).  But no matter... having this here is better than the alternative. :)

**Comment by kozw** [comment]
Good to hear it works. Making XccRemoveIgnorableContent True by default is definitely a good thought, but I'm not sure yet about the consequences for other platforms, like Windows universal projects.

**Comment by Mike-E-angelo** [comment]
true... yeah, it is supposed to be ignorable by nature, but you won't know definitively.  Maybe an xcc: namespace override property would be nice... then we can just copy/paste Xaml and then not have to worry about MSBuild. :)

**Comment by powerdude** [comment]
Hi, i'm having challenges getting this to work.  I'm using a PCL to store my Xamarin forms stuff.  Should the nuget be added to the PCL and the windows project?  Also, the line that has to be added to the csproj.  Should it be added to the PCL project and the windows phone project?  Where should it be added?  I've added it right under the project node and I get an error that it's unrecognized.

**Comment by Mike-E-angelo** [comment]
Xcc should be installed in the same project where the Xaml has the mc:Ignorable tag.  So if your Xaml is in the PCL, you want to put it there.  Make sure you put the property definition in the right place (proj files are terrible and are long overdue for a purge.  I can't wait until someone makes a Xaml-version of MSBuild!!!).  Here is a quick example of where I put mine:
https://github.com/DragonSpark/Framework/blob/Multiversal/DragonSpark.Testing.Client/DragonSpark.Testing.Client.csproj#L21

When I compile, this line is stripped:
https://github.com/DragonSpark/Framework/blob/Multiversal/DragonSpark.Testing.Client/Configuration.xaml#L13

You can look in your obj<configuration>\preprocessedxaml directory to see which files were processed and what the results were.

**Comment by powerdude** [comment]
thanks, got it all working now.
