### ISSUE TITLE
Problem with xaml

### ISSUE THREAD

**Issue by ghua78** [firstfloorsoftware/xcc#5]
Hello, I am writing a game using cocos2d-x 3.7 (windows and windows phone 8.1 universal build c++) and I would like to have my xaml file platform dependant.

```
<Page
x:Class="cocos2d.OpenGLESPage"
xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
xmlns:local="using:cocos2d"
xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
xmlns:win81="condition:DEBUG"
xmlns:wp81="condition:WINDOWS_PHONE_APP"
mc:Ignorable="d win81 wp81"
mc:ProcessContent="win81:* wp81:*">
<win81:SwapChainPanel x:Name="swapChainPanel" Margin="0,0,0,0">
</win81:SwapChainPanel>
</Page>
```

unfortunately while compiling (DEBUG build) system reports:
Error   1   error C2065: 'swapChainPanel' : undeclared identifier

Any idea what could cause it? i tried different conditions: DEBUG, WINDOWS_PHONE
Solution structure is this:
-Windows Project (assets and dlls)
-Windows Phone Project (assets and dlls)
-Shared Project (xaml and cpp files)

Any ideas?
Thank you!

**Comment by kozw** [comment]
SwapChainPanel is moved to default namespace when processed, Consider adding the element to a conditional Grid parent
